name: Print GitHub Actions Variables2

on:
  workflow_dispatch:

jobs:
  print-vars:
    runs-on: ubuntu-latest
    outputs:
        test: ${{ steps.set-output-step.outputs.result }}

    steps:
      - name: Set Output
        id: set-output-step  # idを指定
        run: |
          echo "result=TEST" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub Actions Variables2
        run: |
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.action: ${{ github.action }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref: ${{ github.ref_name }}"
          echo "github.workspace: ${{ github.workspace }}"

  hello:
    needs: print-vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: separate-step-1
        run: |
          readonly BBBB=2222
          echo ${BBBB}

      - name: Use Output from Previous Job
        run: |
          echo " Output from print-vars job: ${{ needs.print-vars.outputs.test }} "
