name: Print GitHub Actions Variables

on:
  workflow_dispatch:

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print GitHub Actions Variables2
        run: |
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.action: ${{ github.action }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.workspace: ${{ github.workspace }}"
