on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD # 'production'は事前にリポジトリのEnvironmentsで設定しておく必要があります
    steps:
      - name: Deploy step
        run: echo "Deploying the application..."

  post-deploy-approve:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: After Approval
        run: echo "Deployment approved! Proceeding..."

  post-deploy-reject:
    needs: deploy
    if: ${{ needs.deploy.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: After Rejection
        run: echo "Deployment rejected. Handling rejection."
