name: Manual Approval Workflow

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approve or Reject'
        required: true
        default: 'approve'
        type: choice
        options:
          - approve
          - reject

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    continue-on-error: true  # ジョブが失敗してもワークフローを続行
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          if [ "${{ github.event.inputs.approval }}" == "approve" ]; then
            echo "Approved! Deploying..."
            # ここにデプロイメントのコマンドを追加
          else
            echo "Rejected! Failing the job."
            exit 1  # ジョブを失敗させて拒否を示す
          fi

  post-deploy-approve:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}  # deploy ジョブが成功した場合
    runs-on: ubuntu-latest
    steps:
      - name: After Approval
        run: echo "Approved! Proceeding with the workflow."

  post-deploy-reject:
    needs: deploy
    if: ${{ needs.deploy.result == 'failure' }}  # deploy ジョブが失敗した場合
    runs-on: ubuntu-latest
    steps:
      - name: Handle Rejection
        run: echo "Rejected. Stopping the workflow."
