on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - uses: actions/checkout@v4

  deploy:
    needs: pre
    runs-on: ubuntu-latest
    environment: PROD
    continue-on-error: true  # ジョブが失敗してもsuccessとしてワークフローを続行してしまうのでなし 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to production..."

  deploy-after:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Post Deploy Actions
        run: |
          echo "${{ needs.deploy.result}}"

